alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias sail='[ -f sail ] && sh sail || sh vendor/bin/sail'
alias sudo='sudo '
alias vim='nvim'
alias code='vscodium'
alias ll='ls -al'
alias lg='lazygit'
